app_monitor/urls.py
from django.contrib import admin
from django.urls import path
from app_monitor.views import dashboard,TemperatureAddRecord,addRecordArduino,addRecordRfid,tempList,deviceView,exportExcel,export_to_excel
from app_monitor.views import django_device,django_device_backtest,deviceViewDetail,export_to_excel_all,devices_all
from app_monitor.views import device_id,export_to_excel_id,arduino_serial_local,additional_text,additional_text_sil,export_to_excel_serial_query
from app_monitor.views import cron_task,scheduler_cihaz,event_list_view,export_to_excel_event_all,export_to_excel_serial_query_deviceid
from app_monitor.filter import filter_device_name,filter_device_id
# from app_monitor.filter import device_filter_id_id,device_filter_sicaklik,device_filter_nem,device_filter_voltaj,device_filter_tarih

# app_name="app_monitor"

urlpatterns=[
    path('',dashboard,name="dashboard"),
    # path('additional_text/<int:id>/<str:additional_text>',additional_text,name="additional_text"),
    path('additional_text_sil/<int:id>',additional_text_sil,name="additional_text_sil"),
    path('additional_text',additional_text,name="additional_text"),
    path('tempList',tempList,name="tempList"), 
    # path('cihazlar/<str:str_device_name>',deviceView,name="deviceView"), #<str:**> parametresi çok dikkatli kullanılmalı,string oldugu için diğer url leri ezmektedir. Ayrıca cihazlar/ şeklinde bir yol da eklenmelidir.
    path('cihazlar/<str:str_device_name>/port=<int:port_no>',deviceView,name="deviceView"), #<str:**> parametresi çok dikkatli kullanılmalı,string oldugu için diğer url leri ezmektedir. Ayrıca cihazlar/ şeklinde bir yol da eklenmelidir.
    # path('cihazlar/<str:str_device_name>/devid=<int:device_id>/port=<int:port_no>',deviceView,name="deviceView"), #<str:**> parametresi çok dikkatli kullanılmalı,string oldugu için diğer url leri ezmektedir. Ayrıca cihazlar/ şeklinde bir yol da eklenmelidir.
    path('cihazlar/<str:str_device_name>/port=<int:port_no>/devid=<int:device_id>',deviceViewDetail,name="deviceViewDetail"), #<str:**> parametresi çok dikkatli kullanılmalı,string oldugu için diğer url leri ezmektedir. Ayrıca cihazlar/ şeklinde bir yol da eklenmelidir.
    path('cihazlar/<int:device_id>',device_id,name="device_id"),
    path('cihazlar_tum',devices_all,name="devices_all"), #<str:**> parametresi çok dikkatli kullanılmalı,string oldugu için diğer url leri ezmektedir. Ayrıca cihazlar/ şeklinde bir yol da eklenmelidir.

    # path('TemperatureAddRecord',TemperatureAddRecord,name="TemperatureAddRecord"),
    path('addRecordArduino',addRecordArduino,name="addRecordArduino"),
    path('addRecordRfid',addRecordRfid,name="addRecordRfid"),
    path('exportExcel',exportExcel,name="exportExcel"),
    path('export_to_excel_serial_query',export_to_excel_serial_query,name="export_to_excel_serial_query"),
    path('export_to_excel_serial_query_deviceid',export_to_excel_serial_query_deviceid,name="export_to_excel_serial_query_deviceid"),
    path('export_to_excel',export_to_excel,name="export_to_excel"),
    path('export_to_excel_all',export_to_excel_all,name="export_to_excel_all"),
    path('export_to_excel_id',export_to_excel_id,name="export_to_excel_id"),
    # path('device_filter',device_filter,name="device_filter"),
    path('filter_device_name',filter_device_name,name="filter_device_name"),
    path('filter_device_id',filter_device_id,name="filter_device_id"),
    # path('device_filter_id_id',device_filter_id_id,name="device_filter_id_id"),
    # path('device_filter_sicaklik',device_filter_sicaklik,name="device_filter_sicaklik"),
    # path('device_filter_nem',device_filter_nem,name="device_filter_nem"),
    # path('device_filter_voltaj',device_filter_voltaj,name="device_filter_voltaj"),
    # path('device_filter_tarih',device_filter_tarih,name="device_filter_tarih"),
    path('django_device',django_device,name="django_device"),
    path('django_device_backtest',django_device_backtest,name="django_device_backtest"),
    path('arduino_serial_local-<str:config_parameter>',arduino_serial_local,name="arduino_serial_local"),
    path('cron_task',cron_task,name="cron_task"),
    path('scheduler_cihaz',scheduler_cihaz,name="scheduler_cihaz"),
    path('event_list_view',event_list_view,name="event_list_view"),
    path('export_to_excel_event_all',export_to_excel_event_all,name="export_to_excel_event_all"),
    


]

app_user_profile/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import login_view,register_view,logout_view

app_name="app_user_profile"

urlpatterns = [
    path('login',login_view,name="login_view"),
    path('logout',logout_view,name="logout_view"),
    path('register',register_view,name="register_view"),
]

project_config/urls.py
from django.contrib import admin
from django.urls import path,include
from app_monitor.views import ilk_def,addRecordArduino,django_device

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app_monitor/',include("app_monitor.urls")),
    path('app_monitor/ilk_def',ilk_def,name="ilk_def"),
    path('addRecordArduino',addRecordArduino,name="addRecordArduino"),
    #USER
    path("user/",include('app_user_profile.urls',namespace="app_user_profile")  ),

]

app_monitor/models.py
from django.db import models


class Device(models.Model):
    device_id=models.IntegerField(primary_key=True,db_column='ID')
    device_name=models.CharField(blank=True,null=True, max_length=20)
    device_ip=models.CharField(blank=True,null=True, max_length=20)
    device_port=models.IntegerField(blank=True,null=True)
    device_function=models.CharField(blank=True,null=True, max_length=20)
    device_state=models.BooleanField(blank=True,null=True,default=False) #241225
    # device_port1=models.BooleanField(default=False) #241225
    # device_port2=models.BooleanField(default=False) #241225

    def __str__(self):
        return(f"{self.device_id}")

class RFID_Kisi(models.Model):
    id=models.IntegerField(primary_key=True,db_column='ID')
    tag_id=models.CharField(blank=True,null=True, max_length=20)
    staff_name=models.CharField(blank=True,null=True, max_length=30)

    def __str__(self):
        return f"{self.tag_id}"


class RFID_Etiket(models.Model):
    id=models.IntegerField(primary_key=True,db_column='ID')
    tag_id=models.ForeignKey(RFID_Kisi,on_delete=models.CASCADE,null=True,blank=True)
    staff_name=models.CharField(blank=True,null=True, max_length=30)
    cikis3=models.CharField(blank=True,null=True, max_length=5)
    date=models.DateTimeField()

    def __str__(self):
        return f"{self.staff_name}--{self.tag_id}"


class Temperature(models.Model):
    id=models.BigAutoField(primary_key=True,db_column='ID')
    temperature=models.FloatField(blank=True,null=True)
    humidity=models.FloatField(blank=True,null=True)
    volcum=models.FloatField(blank=True,null=True)
    date=models.DateTimeField()
    mail=models.BooleanField(default=False)
    additionalText=models.CharField(blank=True,null=True, max_length=50)
    # device_id=models.IntegerField(blank=True,null=True)
    device_id=models.ForeignKey(Device,on_delete=models.CASCADE,null=True, blank=True)
    device_name=models.CharField(blank=True,null=True, max_length=50)
    cikis1=models.CharField(blank=True,null=True, max_length=5)
    cikis2=models.CharField(blank=True,null=True, max_length=5)
    tag_id=models.ForeignKey(RFID_Kisi,on_delete=models.CASCADE,null=True,blank=True)
    staff_name=models.CharField(blank=True,null=True, max_length=30)
    # device_name=models.ForeignKey(Device,on_delete=models.CASCADE,null=True, blank=True)

    def __str__(self):
        return (f"ID:{self.id},Cihaz ID: {self.device_id.device_id} ,Sıcaklık: {self.temperature}, Nem: {self.humidity}, Voltaj: {self.volcum}, Tarih: {self.date}, Cikis1:{self.cikis1}")
    

class Alarm(models.Model):
    id=models.BigAutoField(primary_key=True,db_column='ID')
    alarm_id=models.IntegerField(blank=True,null=True)
    alarm_name=models.CharField(blank=True,null=True, max_length=50)


#Alarmlar: kesinti,port1 down,port2 down,(cihaz bilgisi,saat yok)
#Eventler: kesildi,port1 kesildi (cihaz bilgisi,saat var)

class Event(models.Model):
    id=models.BigAutoField(primary_key=True,db_column='ID')
    device_id=models.ForeignKey(Device,on_delete=models.CASCADE,null=True, blank=True)
    device_name=models.CharField(blank=True,null=True, max_length=50)
    # alarm_id=models.ForeignKey(Alarm,on_delete=models.CASCADE,null=True, blank=True)
    alarm_id=models.IntegerField(blank=True,null=True)
    alarm_name=models.CharField(blank=True,null=True, max_length=50)
    event_active=models.BooleanField(default=True) #alarm devam ediyor mu?  241225
    start_time=models.DateTimeField(blank=True,null=True)
    finish_time=models.DateTimeField(blank=True,null=True)
    info=models.CharField(blank=True,null=True, max_length=50)

    def __str__(self):
        return f"Device name:{self.device_name}--Device ID:{self.device_name}--{self.alarm_name}--{self.start_time}"

app_monitor/templates/app_monitor/arduino_serial.html
{% extends "core/base.html" %}
{% load static %}

{% block title %} <title>CONFIG SAYFASI</title> {% endblock title %}

{% block content %}

<div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show col-sm-6 offset-sm-3" role="alert">
    <strong>{{ message|safe }}</strong> 
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    
        <hr>
        <form action="arduino_serial_local-all" method="get">
            <select name="comport" id="comport">
                <option value="COM1" >COM1</option>
                <option value="COM2">COM2</option>
                <option value="COM3" >COM3</option>
                <option value="COM4" >COM4</option>
                <option value="COM5" selected>COM5</option>
                <option value="COM6">COM6</option>
                <option value="COM7">COM7</option>
                <option value="COM8">COM8</option>
                <option value="COM9">COM9</option>
                <option value="COM10">COM10</option>
            </select>
            <input type="submit" value="VERILERI AL">
        </form>
    {% comment %} <h6>Cihazdan gelen veri: {{value}} </h6> {% endcomment %}
    
    <hr>
{% comment %}     
    <form action="arduino_serial/all" method="get">
    
    <input type="submit" value="GONDER">
    </form>
    
    COMPORT = {{comport}} {% endcomment %}
    {% if comport == "COMxx" %}
    <h3>COMPORT hatalı girdiniz... </h3>
    {% endif %}
    <form action="arduino_serial_local-id" method="get" class="mt-2">
        <input type="text" name="cihaz-id" id="cihaz-id" placeholder="Cihaz ID" value="{{device_id}}">
        <input type="submit" value="Cihaz ID">
    </form>
    <form action="arduino_serial_local-name" method="get" class="mt-2">
        <input type="text" name="cihaz-adi" id="cihaz-adi" placeholder="Cihaz Adı" value="{{device_name}}">
        <input type="submit" value="Cihaz Adı">
    </form>
    <form action="arduino_serial_local-serverip" method="get" class="mt-2">
        <input type="text" name="server-ip" id="server-ip" placeholder="Server IP" value="{{server_ip}}">
        <input type="submit" value="Server IP">
    </form>
    <form action="arduino_serial_local-cihazip" method="get" class="mt-2">
        <input type="text" name="cihaz-ip" id="cihaz-ip" placeholder="Cihaz IP" value="{{device_ip}}">
        <input type="submit" value="Cihaz IP">
    </form>
    <form action="arduino_serial_local-cihazport" method="get" class="mt-2">
        <input type="text" name="cihaz-port" id="cihaz-port" placeholder="Port" value="{{device_port}}">
        <input type="submit" value="PORT">
    </form>
    <form action="arduino_serial_local-gatewayip" method="get" class="mt-2">
        <input type="text" name="default-gateway" id="default-gateway" placeholder="Default Gateway" value="{{ag_gecidi}}">
        <input type="submit" value="Default Gateway">
    </form>
    <form action="arduino_serial_local-ssid" method="get" class="mt-2">
        <input type="text" name="cihaz-ssid" id="ssid" placeholder="SSID" value="{{device_ssid}}">
        <input type="submit" value="SSID">
    </form>
    <form action="arduino_serial_local-password" method="get" class="mt-2">
        <input type="text" name="cihaz-password" id="password" placeholder="Password" value="{{device_password}}">
        <input type="submit" value="Password">
    </form>
    <br>
    <button class="btn btn-danger"><a href="arduino_serial_local-reset" class="text-white text-decoration-none">CIHAZ RESET</a></button>
    <br>
    <h4>{{reset_ok}} </h4>
    
    <h5>BAĞLI PORTLAR</h5>
    <h6>{{port_listesi}} </h6>
    {% comment %} <h3>ARDUINO dan gelen veri: {{value|stringformat:"d"}} </h3> {% endcomment %}
    <h4><a href="/app_monitor" target="_blank">Anasayfa</a></h4>
    </div>

{% endblock content %}

app_monitor/templates/app_monitor/devices_all.html
{% extends "core/base_without_navbar.html" %}
{% comment %} {% extends "core/base.html" %} {% endcomment %}

{% load static %}

{% block title %} <title>TUM CIHAZLAR</title> {% endblock title %}

{% block content %}

{% comment %} {% include "core/navbar.html" %} {% endcomment %}

<div class="container">

    <!-- NAVBAR -->
    <!-- <div class="container-fluid fix-div position-fixed px-0"> -->
        {% comment %} class="container-fluid navbar navbar-expand-lg bg-warning border border-bottom border-dark position-fixed opacity-99 "> {% endcomment %}
        <nav
        class="container-fluid navbar navbar-expand-lg bg-warning border border-bottom border-dark  opacity-99 ">
        <div class="container-fluid py-2 ">
            <a class="navbar-brand" href="/app_monitor">Anasayfa</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown_hover">
                    <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        LİNKLER
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="/app_monitor/arduino_serial_local-all">CIHAZ CONFIG</a></li>
                        <li><a class="dropdown-item" href=" {{ request.user.profile }} ">TÜM CİHAZLAR</a></li>
                    </ul>
                </li>
                
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ request.user.username }}
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href=" {{ request.user.profile }} ">Edit Profile</a></li>
                        <li><a class="dropdown-item" href=" {{ request.user.profile }} ">All {{ request.user.profile }} Posts </a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class=" btn btn-dark text-light px-3 rounded-pill ms-3" href="{% url 'app_user_profile:logout_view' %} ">Çıkış</a>
                </li>
                
                {% else  %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_user_profile:login_view' %} ">Giriş</a>
                </li>
                <li class="nav-item">
                    <a class=" btn btn-dark text-light px-3 rounded-pill ms-3" href="{% url 'app_user_profile:register_view' %} ">Kayıt Ol</a>
                </li>
                {% endif %}
                
            </ul>
            
        </div>
    </div>
</nav>

<!-- NAVBAR END -->

<h3 class="text-center">TUM CIHAZLAR</h3>

<table class="table table-striped tablo-online">
    <th>Cihaz Adı</th>
    <th>Cihaz Id</th>
    <th>Cihaz Port</th>
    <th>Cihaz IP</th>
    <th>Cihaz Fonksiyonu</th>
    <th>Kayıt Sayısı</th>
    <th>Online</th>
    <th>Son Durum</th>
    <th>İlk bağlantı</th>
    {% for devices in devices_all %}
    <tr class="device-row">
        {% comment %} <td><a target="_blank" href="/app_monitor/cihazlar/{{devices.device_name}}/port={{devices.device_port}}/devid={{devices.device_id}}">{{devices.device_name}}</a>  </td> {% endcomment %}
        <td>{{devices.device_name}}</td>
        <td> <a href="/app_monitor/cihazlar/{{devices.device_id}}" target="_blank">{{devices.device_id}}</a></td>
        <td>{{devices.device_port}} </td>
        <td>{{devices.device_ip}} </td>
        <td>{{devices.device_function}} </td>
        <td>{{devices.temperature_set.all.count}} </td>   <!-- device tan temperature modele geçiş, ana model**yardımcı model -->
        <td>    <!-- ONLINE KONTROLU-->

            {% if  devices.device_id in devices_online %}
            <b class="b-online-check" style="background-color: green;padding: 5%;">ONLINE</b> 
            <script>
                //$(".b-online-check").addClass('bg-success');
                //document.getElementsByClassName("b-online-check").style.color="red"
            </script>
            {% else %}
            <b class="b-online-check" style="background-color: red;padding: 5%;">OFFLINE</b> 
            {% endif %}
           
        </td>   <!-- ONLINE KONTROLU-->
        <td>{{devices.temperature_set.last.date|date:"d-m-Y"}} {{devices.temperature_set.last.date|time:"H:i:s"}} </td>   
        {% comment %} <td>{{devices.temperature_set.filter(device_name=devices.device_name).count}} </td> {% endcomment %}
        <td>{{devices.temperature_set.first.date|date:"d-m-Y"}} {{devices.temperature_set.first.date|time:"H:i:s"}} </td>   
    </tr>
    {% endfor %}
</table>

</div>

<script>
    function online_control()
{
    $.ajax({        
              url: 'cihazlar_tum',
              // type: 'POST',
              type: 'GET',
              data:{
              //SicaklikKayit:SicaklikKayit,
              // csrfmiddlewaretoken: '{{ csrf_token }}',
              // dataType: "json",
              },
              // beforeSend: function (xhr){
              //   xhr.setRequestHeader('X-CSRFToken', csrftoken);
              // },
              success: function(response){
              $('.container').html(response);
              console.log("online cihaz durumu yenilendi...")
              },
                              failure: function() {
                          alert("ajax reverse fail geldi");
                            }               
          });
  }
  $(document).ready(online_control()) // sayfa manuel refresh yapıldığında 60 saniye beklemeden ilk kayıdı yapabilmek için. 
                                      //Birden fazla pencerede dashboard açılırsa otomatik 1den fazla kayıt yapılmış olur,hatalı işleme denk gelir.
  $(document).ready(function(){
    setInterval(online_control,20000);
    });
</script>

{% comment %} <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script> <!-- base.html kaldırılırsa yazılır--> {% endcomment %}

{% endblock content %}

app_monitor/templates/app_monitor/events.html
{% extends "core/base.html" %}

{% block title %}
<title>Olaylar</title>
{% endblock title %}

{% block content %}

<script>
    function fetchdata_perf() {
        var events_total_state=document.getElementById("btn-check-all").checked;
        var events_alarm1_state=document.getElementById("btn-check-alarm1").checked;
        var events_alarm2_state=document.getElementById("btn-check-alarm2").checked;
        var events_alarm_clear_state=document.getElementById("btn-check-alarm-clear").checked;
        $.ajax({
          url: 'event_list_view',
          type: 'GET',
          data: {
            events_total_state:events_total_state,
            events_alarm1_state:events_alarm1_state,
            events_alarm2_state:events_alarm2_state,
            events_alarm_clear_state:events_alarm_clear_state,
          },
          success: function (response) {
            $('.event_container').html(response);
            console.log(response);
            console.log("fetchdata_perf success geldi...10 saniye");

          },
          failure: function () {
            alert("ajax reverse fail geldi");
          }
        });
      }
      //$(document).ready(fetchdata_perf()) // sayfa manuel refresh yapıldığında 60 saniye beklemeden ilk kayıdı yapabilmek için. 
      //Birden fazla pencerede dashboard açılırsa otomatik 1den fazla kayıt yapılmış olur,hatalı işleme denk gelir.
      
      
      
       $(document).ready(function () {
        setInterval(fetchdata_perf, 10000);
      }); 

      {% comment %} $(document).ready(function () {
        setInterval( async() => { 
          await  fetchdata_perf() 
        }, 10000);
      }); {% endcomment %}


      {% comment %} setInterval(async () => {
        await fetch("https://jsonplaceholder.typicode.com/todos") 
    }, 100); {% endcomment %}



</script>

<div class="container-fluid p-0">
    <div class="row d-flex ">
        <div class="col-sm-12">
        <input type="checkbox" class="btn-check" id="btn-check-all" onclick="buton_kontrol()" disabled>
        <label class="btn btn-secondary btn-sm my-2" for="btn-check-all">TOPLAM SAYI: {{events_total_count}} </label>
        <input type="checkbox" class="btn-check" id="btn-check-alarm1" onclick="buton_kontrol()" >
        <label class="btn btn-danger btn-sm my-2" for="btn-check-alarm1">KESİNTİ: {{events_alarm1_count}} </label>
        <input type="checkbox" class="btn-check" id="btn-check-alarm2" onclick="buton_kontrol()">
        <label class="btn btn-info btn-sm" for="btn-check-alarm2">ÇIKIŞ ALARM: {{events_alarm2_count}} </label>
        <input type="checkbox" class="btn-check" id="btn-check-alarm-clear" onclick="buton_kontrol()" >
        <label class="btn btn-success btn-sm" for="btn-check-alarm-clear">CLEAR ALARM: {{events_clear_count}} </label>
      </div>
      </div>
<div class="event_container">
<table class="table table-hover" data-click-to-select="true">
    <thead>
       <tr class="bg-primary px-5">
         <th class="ps-5" scope="col">id</th>
         <th scope="col">Cihaz Adı</th>
         <th scope="col">Cihaz ID</th>
         <th scope="col">Alarm ID</th>
         <th scope="col">Alarm Name</th>
         <th scope="col">Event Active</th>
         <th scope="col">Start Time</th>
         <th scope="col">Finish Time</th>
         <th class="pe-5" scope="col">Info</th>
       </tr>
     </thead>
   <tbody>
    {% for event in events %}
     {% comment %} <tr class="{% if event.event_active==True %}bg-danger{% else %}bg-success{% endif %}"> {% endcomment %}

     <tr  
     {% comment %} {% if event.event_active and event.alarm_id is 1 %}class="bg-danger ps-5"{% else %}class="bg-success"{% endif %}  {% endcomment %}
     {% if event.event_active and event.alarm_id is 1 %}class="bg-danger ps-5"{% endif %} 
     {% if event.event_active and event.alarm_id is 2 %}class="bg-info ps-5"{% endif %} 
     {% if not event.event_active  %}class="bg-success ps-5"{% endif %} 
     
     style="margin:20%" >
       <td class="ps-5" >{{event.id}}</td>
       <td >{{event.device_name}}</td>
       <td >{{event.device_id}}</td>
       <td >{{event.alarm_id}}</td>
       <td >{{event.alarm_name}}</td>
       <td > {{event.event_active}}</td> <!--  -->  
       <td >{{event.start_time}}</td>
       <td >{{event.finish_time}}</td>
       <td >{{event.info}}</td>

     </tr>  
     {% endfor %}
   </tbody>
  </table>
  {% comment %} {{datetime_now}} {% endcomment %}
</div><!-- event container sonu -->  
</div><!-- container sonu -->  
<br>

<div class="row">
    <div class="col-sm-6">
     <a href="/app_monitor/export_to_excel_event_all"> <button class="btn btn-success">EXCEL</button> </a> 
    </div>
    <div class="col-sm-6 text-end">
      <h6 ><a href="arduino_serial_local-all" target="_blank">CİHAZ CONFIG</a> </h6>
      <h6 ><a href="/app_monitor/cihazlar_tum" target="_blank">TÜM CİHAZLAR</a>  </h6>
    </div>
  </div>


<script>
    {% comment %} $('#btn-check-alarm1').click(
        function(){alert("btn-check-alarm1 butona tıklandı...")}
      ) {% endcomment %}

      {% comment %} $('#btn-check-alarm1').click(
        function(){alert("btn-check-alarm1 butona tıklandı...")}
      ) {% endcomment %}

      //buton_kontrol() butonların altına alınmalı. Butonların üstünde olursa çalışmıyor. Butonlar daha önce yüklenmeli.
      function buton_kontrol() {
        var events_total_state=document.getElementById("btn-check-all").checked;
        var events_alarm1_state=document.getElementById("btn-check-alarm1").checked;
        var events_alarm2_state=document.getElementById("btn-check-alarm2").checked;
        var events_alarm_clear_state=document.getElementById("btn-check-alarm-clear").checked;
        console.log("buton_kontrol girdi...")
        $.ajax({
          url: 'event_list_view',
          type: 'GET',
          data: {
            events_total_state:events_total_state,
            events_alarm1_state:events_alarm1_state,
            events_alarm2_state:events_alarm2_state,
            events_alarm_clear_state:events_alarm_clear_state,
          },
          success: function (response) {
            $('.event_container').html(response);
            console.log(response);
          },
          failure: function () {
            alert("ajax reverse fail geldi");
          }
        });
      }
</script>

{% endblock content %}

app_monitor/templates/app_monitor/test.html
    <button class="btn btn-danger">Düzenle</button>
    <input type="text">